apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kustomizations.kustomize.toolkit.fluxcd.io
spec:
  group: kustomize.toolkit.fluxcd.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: kustomizations
    singular: kustomization
    kind: Kustomization

