---
- name: Configure kernel parameters for Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Add kernel parameters to /etc/sysctl.d/99-k8s.conf
      copy:
        dest: /etc/sysctl.d/99-k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl parameters
      command: sysctl -p /etc/sysctl.d/99-k8s.conf
