---
- name: Install and configure containerd
  hosts: all
  become: true
  tasks:
    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Configure containerd
      shell: "containerd config default | tee /etc/containerd/config.toml"

    - name: Enable and start containerd service
      systemd:
        name: containerd.service
        enabled: true
        state: started
        restart: always
