---
- name: Install packages
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg2
          - software-properties-common
          - ca-certificates
          - net-tools
          - iftop
        state: present
