- hosts: all
  become: true
  tasks:
    - name: Add kubectl completion and alias to bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          source <(kubectl completion bash)
          alias k=kubectl
          complete -o default -F __start_kubectl k
          alias kaf='k apply -f'
          alias kad='k delete --grace-period 0 --force -f'
          export now='--grace-period 0 --force'
          alias gp='kubectl get po'
          alias gn='kubectl get no'
          alias gd='kubectl get deploy'
          alias gs='kubectl get svc'
          export do='--dry-run=client -o yaml'
          function ns () { 
            kubectl config set-context --current --namespace=$1
          }
